// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL et DATABASE_URL pointent la même connexion directe pour
    // l'instant (voir .env.example) ; DIRECT_URL reste la variable que lit
    // la CLI si un jour les deux divergent à nouveau (ex. retour au pooler).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
