// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // La CLI (migrate, studio) utilise la connexion "session" (DIRECT_URL) :
    // le pooler "transaction" (DATABASE_URL) ne supporte pas les prepared
    // statements dont la CLI a besoin. L'app, elle, continue d'utiliser
    // DATABASE_URL via l'adapter dans src/server/db/prisma.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
